name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - 'release/*'
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .
          docker tag myapp:latest myusername/myapp:latest

      - name: Conditional Tagging and Pushing
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
              echo "Pushing latest tag..."
              docker tag myapp:latest myusername/myapp:latest
              docker push myusername/myapp:latest
          elif [[ "${GITHUB_REF}" == refs/heads/release/* ]]; then
              VERSION_TAG="v1.0.0"  # Replace with dynamic version if needed
              echo "Pushing versioned tag: ${VERSION_TAG}..."
              docker tag myapp:latest myusername/myapp:${VERSION_TAG}
              docker push myusername/myapp:${VERSION_TAG}
          else
              echo "Pushing commit tag: ${GITHUB_SHA}..."
              docker tag myapp:latest myusername/myapp:${GITHUB_SHA}
              docker push myusername/myapp:${GITHUB_SHA}
          fi



